[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons,/mnt/custom-addons
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$X6u1VkrJ2fs/xzjHWOvdmw$uJ8EfHiqb/GZ1FyRp0Dp797S0kPlk1eXYjU5R5j1vMm52fzf1F5LYc4CJiONwll9phEHuKuAkxIb25QgSsDzZw

